name: "Obsidian Genesis Project"
description: "Ultimate AI-agnostic Apple development template with BMAD workflows"
homepageUrl: "https://github.com/zackbissell/obsidian-genesis-template"
topics:
  - apple
  - ios
  - ipados
  - macos
  - visionos
  - watchos
  - tvos
  - swift
  - swiftui
  - swiftdata
  - template
  - ai-development
  - ai-assisted
  - bmad
  - linear
  - project-management
  - enterprise
  - automation
  - claude-code
  - development-template
  - apple-ecosystem
  - swift-6
  - xcode
  - mobile-development
  - cross-platform