name: "Lab Obsidian Genesis Project"
description: "Ultimate AI-agnostic Apple development template with BMAD workflows, designed by Lab Obsidian to set the standard for creative, technical, and narrative-driven projects. Brutalist clarity, no filler."
homepageUrl: "https://www.labobsidian.com"
topics:
  - lab-obsidian
  - apple
  - ios
  - ipados
  - macos
  - visionos
  - watchos
  - tvos
  - swift
  - swiftui
  - swiftdata
  - template
  - ai-development
  - ai-assisted
  - bmad
  - linear
  - project-management
  - enterprise
  - automation
  - claude-code
  - development-template
  - apple-ecosystem
  - swift-6
  - xcode
  - mobile-development
  - cross-platform
  - brutalist-design