version: 4.29.0
markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments:
  - Documentation/Technical/Architecture.md
  - Documentation/Technical/YourProjectName-Technical-Architecture.md
  - CLAUDE.md
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
  - docs/architecture/apple-ecosystem-integration.md
  - docs/architecture/development-patterns.md
  - docs/architecture/swift-6-concurrency-patterns.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: YourProjectName
coreProjectLocation:
  devStoryLocation: docs/stories
  devLoadAlwaysFiles:
    - docs/architecture/coding-standards.md
    - docs/architecture/tech-stack.md
    - docs/architecture/source-tree.md
    - docs/architecture/apple-ecosystem-integration.md
    - docs/architecture/development-patterns.md
    - docs/architecture/swift-6-concurrency-patterns.md
  devDebugLog: .ai/debug-log.md
  agentCoreDump: .ai/core-dump{n}.md